# å¤´åƒ
avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜€
    message: ä¸æƒ³ä¸Šå­¦
# ç‚¹å‡»çƒŸèŠ±
fireworks:
  enable: false
  # colors:
  #   - '102, 167, 221'
  #   - '62, 131, 225'
  #   - '33, 78, 194'
# ç¤¾äº¤å›¾æ ‡
social:
  - name: GitHub
    link: https://github.com/Yuyang-Hou
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:508701891@qq.com
    icon: ri:mail-line
    color: '#8E71C1'
    # - name: Telphone
    # link: 17873163001
    # icon: ri:phone-line
    # color: '#8E71C1'
      # - name: RSS
  #   # set rss in your root config
  #   # https://github.com/hexojs/hexo-generator-feed
  #   link: /atom.xml # config.feed.path
  #   icon: ri:rss-line
  #   color: orange
  # - name: ç½‘æ˜“äº‘éŸ³ä¹
  #   link: https://music.163.com/#/user/home?id=247102977
  #   icon: ri:netease-cloud-music-line
  #   color: '#C10D0C'
  # - name: å“”å“©å“”å“©åŠ¨ç”»
  #   link: https://space.bilibili.com/1579790
  #   icon: ri:bilibili-line
  #   color: '#FF8EB3'
  # - name: å¾®ä¿¡å…¬ä¼—å·
  #   link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
  #   icon: ri:wechat-2-line
  #   color: '#1AAD19'
  # - name: Twitter
  #   link: https://twitter.com/YunYouJun
  #   icon: ri:twitter-line
  #   color: '#1da1f2'
  # - name: Telegram
  #   link: https://t.me/YunYouJun
  #   icon: ri:telegram-line
  #   color: '#0088CC'
  # - name: Telegram Channel
  #   link: https://t.me/elpsycn
  #   icon: ri:telegram-fill
  #   color: '#0088CC'
  # - name: Travelling
  #   link: https://travellings.link
  #   icon: ri:send-plane-2-line
  #   color: black

reward:
  enable: false

footer:
  powered:
    enable: false

post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: true

wordcloud:
  enable: true

comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œå»ºè®®è·³è½¬ GitHub Issues è¯„è®ºã€‚
    - è‹¥æ²¡æœ‰æœ¬æ–‡ Issueï¼Œæ‚¨å¯ä»¥ä½¿ç”¨ Comment æ¨¡ç‰ˆæ–°å»ºã€‚
  candidates:
    - waline
    - utterances

banner:
  enable: true
  title: ä¸€åªçŒ«çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
favicon: /favicon.svg

